### ISSUE TITLE
Checkbox in dashboard datafeed wrong

### ISSUE THREAD

**Issue by mikelpalokaj** [effectai/effect-dashboard#117]
The small tickbox on the dashboard says " You voted: Yes".
Also when actually voted no :)
(I voted no on #89 for example)

![image](https://user-images.githubusercontent.com/35257431/148239931-b8588f5a-32ca-4f0b-b38c-146b63339234.png)

**Comment by rochelle8044** [comment]
I believe it's for if you voted or not, not your actual vote. I can confirm it's working for me correctly. Perhaps we need to change the message to, 'Vote submitted: Yes/No'.

**Comment by jabbarn** [comment]
Hi there, the feature that shouldve been implemented was showing what your vote answer is for a particular proposal, but for some reason it didnt show that correctly. Thats why some thought it might be if you actually have voted or not, my apologies but it should be fixed now with the PR mentioned above.

**Comment by mikelpalokaj** [comment]
Tnx Jabbarn :)
