### ISSUE TITLE
Show active proposals on top in the proposal list

### ISSUE THREAD

**Issue by jeisses** [effectai/effect-dashboard#61]
At the moment "Processing" proposals are shown above "Active".
Also on Chrome the sorting appears to be broken (Draft proposals showing on top) while sorting on Firefox works

**Comment by jeisses** [comment]
On Chrome proposals in draft are still shown on top, with the oldest first (@bommels )

**Comment by jeisses** [comment]
This is still not fixed. The current proposal order on Firefox is strange as an active and a draft proposal appear in the middle of the list.

I would like to just show the "Active", "Pending" and "Processing" proposals under de "All" tab in that order (so hide the Drafts)

**Comment by djmbritt** [comment]
- [ ] Remove `pending` tab
- [ ] Add all `pending` votes to the `active` tab
- [ ] Fix sorting `All` tab.
