### ISSUE TITLE
Fetch cycle stats on the Token Map dynamically

### ISSUE THREAD

**Issue by jeisses** [effectai/effect-dashboard#68]
# Feature 

Update the cycle start date on the token map

## Description

This cycle start date on the token map is currently hard coded and outdated, it should be fetched from blockchain.

**Comment by jeisses** [comment]
I'm still reviewing the PR (https://github.com/effectai/effect-dashboard/pull/86). This will be resolved soon

**Comment by laurensV** [comment]
https://github.com/effectai/effect-dashboard/pull/96 implemented this.
