### ISSUE TITLE
Mobile view issues

### ISSUE THREAD

**Issue by djmbritt** [effectai/effect-dashboard#69]
At the moment there are a couple of bugs in the visualization of the app. 

---

In the dropdown menu the connect button isn't properly positioned.
![image](https://user-images.githubusercontent.com/3985738/110465914-535e2400-80d5-11eb-9048-97de803b68f0.png)

---

DAO members page
![image](https://user-images.githubusercontent.com/3985738/110467215-08451080-80d7-11eb-9526-dc43a3d5d7b2.png)

---

When trying to connect a wallet, and the flow fails, it presents the error within the overlay of the "connect wallet interface". Ideally, there would be a modal pop up that notifies the user when it fails. Or the option to guide the user to a page where they can download and use the wallet of their choice.
https://user-images.githubusercontent.com/3985738/110467075-d764db80-80d6-11eb-80a6-8c9ab6cd771f.mp4

---

When the page is smaller than 1220 pixels wide, the menubar collapses incorrectly.
![image](https://user-images.githubusercontent.com/3985738/110467907-ded8b480-80d7-11eb-8f81-e1e88396ab48.png)

---

The __Other Resources__  feels like it should be somewhere more visible, maybe in its own page or in the profile page. And more documentation and examples should be provided on how to create a wallet and stake funds. 

---

And I think I got kicked out of my login session when a cycle ended. Not even sure if that's what happened. But the coincidence does make me think that was the case. Not sure if this behavior can be avoided.

**Comment by jeisses** [comment]
@djmbritt are these issues now resolved?

**Comment by djmbritt** [comment]
Except for getting kicked out when the cycle ends, which I'm still not sure of, yes!
