### ISSUE TITLE
Fix Quorum for legacy proposals to be original amount

### ISSUE THREAD

**Issue by djstrikanova** [effectai/effect-dashboard#89]
https://dao.effect.network/proposals/22

The new p22 quorum is displayed for legacy proposals, fix to prevent future confusion to new people in future

**Comment by jeisses** [comment]
Good catch. This is a bug in the frontend; the quorum should be fetched from the cycle table that the proposal belongs to, not from the config table

**Comment by jeisses** [comment]
Fixed in https://github.com/effectai/effect-dashboard/pull/91
