### ISSUE TITLE
Greymass Connection Status

### ISSUE THREAD

**Issue by djstrikanova** [effectai/effect-dashboard#93]
I thought it might be useful for a small "Connection Status" box to appear somewhere so layman users understand it's not the Dashboard itself breaking but Graymass having connectivity issues.

**Comment by jeisses** [comment]
Thanks for raising the issue.
I think a connection status would be hard to implement; we wouldn't know if the node is functioning properly and is able to send transactions.

I would prefer to tackle this by providing more reliable nodes or fall-back nodes. The node we're using now seems to be stable lately but if that changes we can create a new ticket :)
